[package]
name = "nft-swap-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.nft-swap]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.31.0"
